spring:
  application:
    name: rabbitmq-customer
  # 数据库链接配置
  datasource:
    url: jdbc:mysql://192.168.1.215:3306/yccpy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yccpy
    password: XJd35b1QhM!
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000

  #MQ配置
  rabbitmq:
    host: 192.168.1.217
    port: 5672
    username: station
    password: d4A2TX8U$r
    virtual-host: station_test

  #mq配置
  redis:
    # 地址
    #    host: localhost
    host: 192.168.1.215
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: LAblHBlWnQ!@#
